### ISSUE TITLE
Are these for sale?

### ISSUE THREAD

**Issue by znmeb** [DatanoiseTV/PicoDSP-Hardware#1]
Are these for sale? If so, do you ship to the USA? Are there boards with male headers soldered on?

**Comment by DatanoiseTV** [comment]
@znmeb Please drop me an E-Mail to syso(at)datanoise(dot)org

**Comment by sillycowvalley** [comment]
https://shop.datanoise.org/products/picoadk

**Comment by DatanoiseTV** [comment]
yes! but only a bunch left On 9. Mar 2024, at 23:02, sillycowvalley ***@***.***> wrote:﻿
https://shop.datanoise.org/products/picoadk

**Comment by jasonolan** [comment]
Rather late to the party, but am wondering whether there are any of these around for sale? v2 on the 2350 board?
